### ISSUE TITLE
Read Timecode Metadata

### ISSUE THREAD

**Issue by chrisspiegl** [arikrupnik/ltcsync#29] opened 2020-11-09 13:40 UTC
Hello @arikrupnik, I just tried syncing some files that don't all have audio TC and noticed that Meta Data Timecode information is not read for sync purposes?

**Usecase:**

- The Zoom F6 for example tags the metadata into the audio files as they are being recorded.
- The audio TC would then be recorded by another device (most likely a camera).
- The LTCsync would then read the Audio TC and the Meta Data TC and sync them.

**Current Situation:**

LTCsync only synchronizes the audio TC channels. But audio recorders for example would then need to also record a audio TC track which is kind of redundant I would say.

I am not sure how this would be "easily" implemented. One would have to figure out how the metadata TC data is stored in different file types (audio files vs video files etc…).

**Comment by arikrupnik** [comment] 2020-11-09 17:00
Duplicate of issue #18 

Please add details of your recorder in the same format as existing entries--a snippet of `ffprobe` output.

**Closed as completed by arikrupnik** 2020-11-09 17:00 UTC
Labels: duplicate
